### ISSUE TITLE
There should be a direct programatic way to check whether any javascript error has occurred due to running some test(s).

### ISSUE THREAD

**Issue by HaseebLUMS** [Codeception/module-webdriver#25]
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by SOHELAHMED7** [comment]
This can be achieved.

#### Step: 1

Codeception Config: 

File: acceptancejs.suite.yml (this can be different in your case)

```yaml
actor: AcceptanceJsTester

modules:
    enabled:
        - Asserts
        # use WebDriver instead of PhpBrowser to enable javascript testing
        -   WebDriver:
                url: 'http://localhost:8116/'
                #url: https://web/
                #host: chrome
                debug_log_entries: 10 # <------ this is the most important one; it must be > 0 
                log_js_errors: true # <------ this won't work if `debug_log_entries` is 0 (the default value)
                browser: chrome
                window_size: 1900x950
                capabilities:
                    javascriptEnabled: true
```

Till now if you test fails for any reason, the client side JavaScript (browser devtool console) error will be displayed as comment in CLI. But if you tests passes, it won't be shown.

But we want to see errors and want to fail tests if there are any such errors.

Below steps are for that.

#### Step: 2

In your test/cest file:

```php
use Codeception\Module\WebDriver;

class ProfileControllerCest 
{
    public $wd;

    protected function _inject(WebDriver $wd)
    {
        $this->wd = $wd;
    }

    public function testSomething(AcceptanceJsTester $I)
    {
        // your actual tests that may yield client side JS errors
    }

   public function _after(AcceptanceJsTester $I)
    {
        $this->failIfBrowserConsoleJavaScriptErrorsExists($I, $this->wd);
        parent::_after($I);
    }

    protected function failIfBrowserConsoleJavaScriptErrorsExists(AcceptanceJsTester $I)
    {
        // $I->wait(3); // depending on your tests, you may "wait" for JS operations to finish
        $clientSideErrors = $this->getClientSideErrors();
        if ($clientSideErrors) {
            // $I->fail('JavsScript (JS) error found in browser devtools console!');
            $I->assertNull($clientSideErrors);
        }
    }

    protected function getClientSideErrors()
    {
        $logs = $this->wd->webDriver->manage()->getAvailableLogTypes();
        $logType = 'browser';
        if (in_array($logType, $logs)) {
            return $this->wd->webDriver->manage()->getLog($logType);
        }
        return [];
    }
```

Also if you navigate from one page to another in test and if first one have errors and second does not then you have to handle this in your own way

---

Things to do in Codeception:

 - fix incorrect documentation regarding `log_js_errors` (PR https://github.com/Codeception/module-webdriver/pull/129)
 - add public method to get all JS errors in tests
 - add a suite config to allow failure of tests if JS errors exist
